### ISSUE TITLE
💡 [Feature]: UI update for more contemporary look

### ISSUE THREAD

**Issue by koustov** [atapas/webapis-playground#51]
**Is your feature request related to a problem? Please describe.**
This is a great application without a single doubt. A more contemporary aesthetic will be icing on the cake.

**Describe the solution you'd like**
A modern UI transformation

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hendaoui** [comment]
Assign it to me please, I'll work on it!

**Comment by atapas** [comment]
> Assign it to me please, I'll work on it!

Assigned. Could you please put forward your proposal first. We may want to review it before you start. Just to save on time :)

cc: @koustov

**Comment by atapas** [comment]
@all-contributors please add @koustov  for Bug

**Comment by atapas** [comment]
@hendaoui , I see the assignment was removed.. Not sure, if that was accidental...Please let me know. I have assigned to you again.

**Comment by mverissimo** [comment]
Hello, I start working on this a day ago and I did draft a PR(#75), I would like to continue working on this, but the PR was assigned to another, maybe we can work together.

**Comment by atapas** [comment]
Hello @mverissimo , I'm actually waiting for a confirmation from @hendaoui if he still owns this issue as I have seen the removal of assignment once. If he is not owning it, you can own it completely. Otherwise, I would suggest you both work together on this.

There is one more issue, https://github.com/atapas/webapis-playground/issues/27 that Bharati is working on. She is designing a landing page with hero images and other high-level information. So I would suggest you have sync up with her as well. The entire look and feel of the app should not differ from page to page.

Also, I am available for any quick sync-up.

**Comment by mverissimo** [comment]
@atapas  Goood, I waiting for the @hendaoui response to continue with this, and we sync up later to discuss more about the landing page! Thanks.

**Comment by max-programming** [comment]
I think using Tailwind is better. We could use something like [daisyui](https://daisyui.com)
